spring.application.name=store
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/jyn_store}
server.port=${PORT:8080}

# Configuración de carga de archivos (para imágenes de productos)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Habilitar actualizaciones automáticas de plantillas/estáticos durante el desarrollo
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Configuración de codificación UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
